// <auto-generated />
using System;
using DIS_data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DIS_data.Migrations
{
    [DbContext(typeof(DisContext))]
    [Migration("20220529204810_History")]
    partial class History
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.2.21154.2")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DIS_data.Entity.HistoryTransactionEntity", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("Amount");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MoneyType");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("TranDate");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TransactionType");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserLogin");

                    b.HasKey("TransactionId");

                    b.HasAlternateKey("UserLogin", "TransactionTime");

                    b.ToTable("History");
                });

            modelBuilder.Entity("DIS_data.Entity.UserEntity", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("Login");

                    b.Property<bool>("IsUserConfitmed")
                        .HasColumnType("boolean")
                        .HasColumnName("Confirmed");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.HasKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DIS_data.Entity.HistoryTransactionEntity", b =>
                {
                    b.HasOne("DIS_data.Entity.UserEntity", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserLogin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DIS_data.Entity.UserEntity", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
